auth:
- auth_name: client
  auth_type: signed_headers
base_image: python
build_args:
- name: arg1
  required_arg: false
  type: integer
meta:
  author: fake author
  author_email: fake@gmail.com
  git: https://github.com/vinalb-oblivious/sample-repo.git
  service_name: Sample Service
  version: 0.0.1
paths:
- access: role1
  path: /
  short_description: test path for test role
roles:
- role_auth: client
  role_cardinality: 4
  role_description: Role1
  role_name: role1
traffic:
- connect: '::::'
  direction: inbound
  name: main_io
  port: 80
